# Generated by Django 5.1.7 on 2025-03-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_expense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
    ]
